FROM python:3.12-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    libgl1 \
    libglib2.0-0 \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

RUN pip install --no-cache-dir ultralytics Pillow

COPY train.py .
COPY dataset/dataset.yaml dataset/dataset.yaml

CMD ["python", "train.py", "--epochs", "50", "--batch", "16", "--workers", "4", "--device", "0"]
